package Digilinc;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
public class AdminPanel extends javax.swing.JFrame 
{
    private static final long serialVersionUID = 8127012195410269301L;
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rst=null;
    Statement stmt=null;
    int sessionid;
    String suser,stype;
    DefaultTableModel model,model1;
    public AdminPanel(String username, String usertype, String sid) 
    {
        initComponents();
        getContentPane().setBackground(Color.decode("#313d48"));
        
        sessionid =Integer.parseInt(sid);
        suser = username;
        stype = usertype;
        model = new DefaultTableModel();
        model.addColumn("Prescription Name");
        model.addColumn("Purpose");
        tblpres.setModel(model);
        model1 = new DefaultTableModel();
        model1.addColumn("Disease Name");
        model1.addColumn("Description");
        tblpres1.setModel(model1);
        //UIManager.put("TabbedPane.selected", Color.decode("#13a6d9"));
        tblpres.setFillsViewportHeight(true);
        tblpres1.setFillsViewportHeight(true);
        jScrollPane4.getViewport().setBackground(Color.decode("#313d48"));
        jScrollPane5.getViewport().setBackground(Color.decode("#313d48"));
        JTableHeader header = tblpres.getTableHeader();
        header.setBackground(Color.decode("#313d48"));
        header.setForeground(Color.WHITE);
        JTableHeader header1 = tblpres1.getTableHeader();
        header1.setBackground(Color.decode("#313d48"));
        header1.setForeground(Color.WHITE);
        tblpres.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 24));
        tblpres1.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 24));
        this.setIconImage(new ImageIcon(getClass().getResource("icon.ico")).getImage());  
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cms","root","");
        } 
        catch (SQLException | ClassNotFoundException ex ) 
        {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!username.equals(""))
        {
            suser = username;
        }
        this.pack();
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Users = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtchangepassusrname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnchangepass = new javax.swing.JButton();
        txtchangepasspass = new javax.swing.JPasswordField();
        txtchangepassnewpass = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        DocDetails = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdoc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtmob = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cmbdegree = new javax.swing.JComboBox<>();
        txtspec = new javax.swing.JTextField();
        txtmrno = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        btndocsave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        Prescription = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblpres = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtppname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        cmbdisease = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        cmbpresname = new javax.swing.JComboBox<>();
        jLabel143 = new javax.swing.JLabel();
        Disease = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblpres1 = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtdiseasename = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        txtdesc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        cmbdiseasename = new javax.swing.JComboBox<>();
        jLabel144 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        btnhomelogout = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VPS Clinic Management System");
        setBackground(new java.awt.Color(49, 61, 72));
        setForeground(new java.awt.Color(49, 61, 72));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 738));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(49, 61, 72));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1366, 670));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        Users.setBackground(new java.awt.Color(49, 61, 72));
        Users.setPreferredSize(new java.awt.Dimension(1360, 670));

        jPanel5.setBackground(new java.awt.Color(49, 61, 72));
        jPanel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(1360, 670));

        jPanel15.setBackground(new java.awt.Color(49, 61, 72));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(19, 166, 217))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(49, 61, 72));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username:");

        jLabel7.setBackground(new java.awt.Color(49, 61, 72));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Old Password:");

        jLabel8.setBackground(new java.awt.Color(49, 61, 72));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New Password:");

        txtchangepassusrname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtchangepassusrname.setForeground(new java.awt.Color(255, 255, 255));
        txtchangepassusrname.setBorder(null);
        txtchangepassusrname.setCaretColor(new java.awt.Color(255, 255, 255));
        txtchangepassusrname.setOpaque(false);

        jButton3.setBackground(new java.awt.Color(19, 166, 217));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnchangepass.setBackground(new java.awt.Color(19, 166, 217));
        btnchangepass.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnchangepass.setForeground(new java.awt.Color(255, 255, 255));
        btnchangepass.setText("Update");
        btnchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangepassActionPerformed(evt);
            }
        });

        txtchangepasspass.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtchangepasspass.setForeground(new java.awt.Color(255, 255, 255));
        txtchangepasspass.setBorder(null);
        txtchangepasspass.setCaretColor(new java.awt.Color(255, 255, 255));
        txtchangepasspass.setOpaque(false);

        txtchangepassnewpass.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtchangepassnewpass.setForeground(new java.awt.Color(255, 255, 255));
        txtchangepassnewpass.setBorder(null);
        txtchangepassnewpass.setCaretColor(new java.awt.Color(255, 255, 255));
        txtchangepassnewpass.setOpaque(false);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnchangepass, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addComponent(txtchangepassusrname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtchangepasspass, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtchangepassnewpass, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtchangepassusrname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(txtchangepasspass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(txtchangepassnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(btnchangepass))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/changepassword.png"))); // NOI18N

        jLabel141.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 255, 255));
        jLabel141.setText("VPS TecHub Pvt. Ltd.");
        jLabel141.setPreferredSize(new java.awt.Dimension(173, 50));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(551, 551, 551)
                        .addComponent(jLabel141, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jLabel141, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UsersLayout = new javax.swing.GroupLayout(Users);
        Users.setLayout(UsersLayout);
        UsersLayout.setHorizontalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        UsersLayout.setVerticalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Details", Users);

        DocDetails.setBackground(new java.awt.Color(49, 61, 72));
        DocDetails.setPreferredSize(new java.awt.Dimension(1360, 670));

        jPanel7.setBackground(new java.awt.Color(49, 61, 72));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(19, 166, 217))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        jLabel13.setBackground(new java.awt.Color(49, 61, 72));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Doctor Name:");

        jLabel15.setBackground(new java.awt.Color(49, 61, 72));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email - Id:");

        jLabel16.setBackground(new java.awt.Color(49, 61, 72));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mobile No:");

        jLabel17.setBackground(new java.awt.Color(49, 61, 72));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Professional Degree:");

        jLabel18.setBackground(new java.awt.Color(49, 61, 72));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Specialization:");

        jLabel19.setBackground(new java.awt.Color(49, 61, 72));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Medical Reg. No:");

        jLabel20.setBackground(new java.awt.Color(49, 61, 72));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Address:");

        txtdoc.setBackground(new java.awt.Color(49, 61, 72));
        txtdoc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtdoc.setForeground(new java.awt.Color(255, 255, 255));
        txtdoc.setBorder(null);
        txtdoc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdoc.setOpaque(false);
        txtdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(49, 61, 72));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DR.");

        txtmob.setBackground(new java.awt.Color(49, 61, 72));
        txtmob.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtmob.setForeground(new java.awt.Color(255, 255, 255));
        txtmob.setBorder(null);
        txtmob.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmob.setOpaque(false);

        txtemail.setBackground(new java.awt.Color(49, 61, 72));
        txtemail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(null);
        txtemail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtemail.setOpaque(false);

        cmbdegree.setBackground(new java.awt.Color(49, 61, 72));
        cmbdegree.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbdegree.setForeground(new java.awt.Color(255, 255, 255));
        cmbdegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MBBS", "BHMS", "BAMS" }));
        cmbdegree.setBorder(null);
        cmbdegree.setOpaque(false);

        txtspec.setBackground(new java.awt.Color(49, 61, 72));
        txtspec.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtspec.setForeground(new java.awt.Color(255, 255, 255));
        txtspec.setBorder(null);
        txtspec.setCaretColor(new java.awt.Color(255, 255, 255));
        txtspec.setOpaque(false);

        txtmrno.setBackground(new java.awt.Color(49, 61, 72));
        txtmrno.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtmrno.setForeground(new java.awt.Color(255, 255, 255));
        txtmrno.setBorder(null);
        txtmrno.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmrno.setOpaque(false);

        txtaddress.setBackground(new java.awt.Color(49, 61, 72));
        txtaddress.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(255, 255, 255));
        txtaddress.setBorder(null);
        txtaddress.setCaretColor(new java.awt.Color(255, 255, 255));
        txtaddress.setOpaque(false);

        btndocsave.setBackground(new java.awt.Color(19, 166, 217));
        btndocsave.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btndocsave.setForeground(new java.awt.Color(255, 255, 255));
        btndocsave.setText("Update");
        btndocsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocsaveActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(19, 166, 217));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btndocsave)
                .addGap(217, 217, 217)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmob)
                                    .addComponent(jSeparator8)
                                    .addComponent(cmbdegree, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtmrno, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                            .addComponent(jSeparator9)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                                    .addComponent(txtdoc)))
                            .addComponent(txtaddress)
                            .addComponent(jSeparator12)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtspec, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(101, 101, 101))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel21))))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtmrno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbdegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btndocsave))
                .addGap(15, 15, 15))
        );

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/People-Doctor-Male-icon.png"))); // NOI18N

        jLabel142.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(255, 255, 255));
        jLabel142.setText("VPS TecHub Pvt. Ltd.");
        jLabel142.setPreferredSize(new java.awt.Dimension(173, 50));

        javax.swing.GroupLayout DocDetailsLayout = new javax.swing.GroupLayout(DocDetails);
        DocDetails.setLayout(DocDetailsLayout);
        DocDetailsLayout.setHorizontalGroup(
            DocDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocDetailsLayout.createSequentialGroup()
                .addGroup(DocDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocDetailsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel22)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DocDetailsLayout.createSequentialGroup()
                        .addGap(688, 688, 688)
                        .addComponent(jLabel142, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(328, 328, 328))
        );
        DocDetailsLayout.setVerticalGroup(
            DocDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocDetailsLayout.createSequentialGroup()
                .addGroup(DocDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocDetailsLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DocDetailsLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addComponent(jLabel142, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doctor Details", DocDetails);

        Prescription.setBackground(new java.awt.Color(49, 61, 72));
        Prescription.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Prescription.setPreferredSize(new java.awt.Dimension(1360, 670));
        Prescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrescriptionMouseClicked(evt);
            }
        });

        jScrollPane4.setBackground(new java.awt.Color(49, 61, 72));
        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblpres.setBackground(new java.awt.Color(49, 61, 72));
        tblpres.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblpres.setForeground(new java.awt.Color(255, 255, 255));
        tblpres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblpres.setGridColor(new java.awt.Color(49, 61, 72));
        tblpres.setOpaque(false);
        jScrollPane4.setViewportView(tblpres);

        jPanel14.setBackground(new java.awt.Color(49, 61, 72));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Prescription", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(19, 166, 217))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(49, 61, 72));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");

        txtppname.setBackground(new java.awt.Color(49, 61, 72));
        txtppname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtppname.setForeground(new java.awt.Color(255, 255, 255));
        txtppname.setBorder(null);
        txtppname.setCaretColor(new java.awt.Color(255, 255, 255));
        txtppname.setOpaque(false);

        jLabel9.setBackground(new java.awt.Color(49, 61, 72));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Purpose:");

        jButton6.setBackground(new java.awt.Color(19, 166, 217));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cmbdisease.setBackground(new java.awt.Color(49, 61, 72));
        cmbdisease.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbdisease.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator13)
                    .addComponent(txtppname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cmbdisease, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtppname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbdisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(49, 61, 72));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Prescription", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(19, 166, 217))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(49, 61, 72));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Name:");

        jButton7.setBackground(new java.awt.Color(19, 166, 217));
        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cmbpresname.setBackground(new java.awt.Color(49, 61, 72));
        cmbpresname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbpresname.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136)
                .addComponent(cmbpresname, 0, 232, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbpresname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jLabel143.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(255, 255, 255));
        jLabel143.setText("VPS TecHub Pvt. Ltd.");
        jLabel143.setPreferredSize(new java.awt.Dimension(173, 50));

        javax.swing.GroupLayout PrescriptionLayout = new javax.swing.GroupLayout(Prescription);
        Prescription.setLayout(PrescriptionLayout);
        PrescriptionLayout.setHorizontalGroup(
            PrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescriptionLayout.createSequentialGroup()
                .addGroup(PrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrescriptionLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PrescriptionLayout.createSequentialGroup()
                        .addGap(569, 569, 569)
                        .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(368, 368, 368))
        );
        PrescriptionLayout.setVerticalGroup(
            PrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescriptionLayout.createSequentialGroup()
                .addGroup(PrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrescriptionLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PrescriptionLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prescription", Prescription);

        Disease.setBackground(new java.awt.Color(49, 61, 72));
        Disease.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Disease.setPreferredSize(new java.awt.Dimension(1360, 670));
        Disease.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiseaseMouseClicked(evt);
            }
        });

        jScrollPane5.setBackground(new java.awt.Color(49, 61, 72));
        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(255, 255, 255));

        tblpres1.setBackground(new java.awt.Color(49, 61, 72));
        tblpres1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblpres1.setForeground(new java.awt.Color(255, 255, 255));
        tblpres1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblpres1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblpres1.setGridColor(new java.awt.Color(49, 61, 72));
        tblpres1.setOpaque(false);
        jScrollPane5.setViewportView(tblpres1);

        jPanel18.setBackground(new java.awt.Color(49, 61, 72));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Ailments", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(19, 166, 217))); // NOI18N

        jLabel23.setBackground(new java.awt.Color(49, 61, 72));
        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Name:");

        txtdiseasename.setBackground(new java.awt.Color(49, 61, 72));
        txtdiseasename.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtdiseasename.setForeground(new java.awt.Color(255, 255, 255));
        txtdiseasename.setBorder(null);
        txtdiseasename.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdiseasename.setOpaque(false);

        jButton8.setBackground(new java.awt.Color(19, 166, 217));
        jButton8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txtdesc.setBackground(new java.awt.Color(49, 61, 72));
        txtdesc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(255, 255, 255));
        txtdesc.setBorder(null);
        txtdesc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdesc.setOpaque(false);

        jLabel24.setBackground(new java.awt.Color(49, 61, 72));
        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Description:");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel18Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel18Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(109, 109, 109)
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator14)
                                        .addComponent(txtdiseasename, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiseasename, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(49, 61, 72));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Ailments", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(19, 166, 217))); // NOI18N

        jLabel25.setBackground(new java.awt.Color(49, 61, 72));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Name:");

        jButton9.setBackground(new java.awt.Color(19, 166, 217));
        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cmbdiseasename.setBackground(new java.awt.Color(49, 61, 72));
        cmbdiseasename.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbdiseasename.setForeground(new java.awt.Color(255, 255, 255));
        cmbdiseasename.setOpaque(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel25)
                        .addGap(73, 73, 73)
                        .addComponent(cmbdiseasename, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbdiseasename, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jLabel144.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(255, 255, 255));
        jLabel144.setText("VPS TecHub Pvt. Ltd.");
        jLabel144.setPreferredSize(new java.awt.Dimension(173, 50));

        javax.swing.GroupLayout DiseaseLayout = new javax.swing.GroupLayout(Disease);
        Disease.setLayout(DiseaseLayout);
        DiseaseLayout.setHorizontalGroup(
            DiseaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiseaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DiseaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406))
            .addGroup(DiseaseLayout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DiseaseLayout.setVerticalGroup(
            DiseaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiseaseLayout.createSequentialGroup()
                .addGroup(DiseaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiseaseLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DiseaseLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ailments", Disease);

        jPanel8.setBackground(new java.awt.Color(19, 166, 217));
        jPanel8.setPreferredSize(new java.awt.Dimension(1299, 45));

        jLabel28.setBackground(new java.awt.Color(49, 61, 72));
        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("VPS TecHub Pvt Ltd Clinic Management System");

        jButton12.setBackground(new java.awt.Color(19, 166, 217));
        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Home");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnhomelogout.setBackground(new java.awt.Color(19, 166, 217));
        btnhomelogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnhomelogout.setForeground(new java.awt.Color(255, 255, 255));
        btnhomelogout.setText("Logout");
        btnhomelogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomelogoutActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/logoicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel29)
                .addGap(30, 30, 30)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 558, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(51, 51, 51)
                .addComponent(btnhomelogout)
                .addGap(44, 44, 44))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnhomelogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/Close Window_48px_3.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loaddname()
    {     
        ArrayList<String> list = new ArrayList<>();
        try 
        {
            stmt = conn.createStatement();
            String query =  "select dname from doctor";
            rst = stmt.executeQuery(query);
            while(rst.next())
            {
                list.add(rst.getString("dname"));
            }
        }
        catch(SQLException ex)
        {
            System.out.println(ex);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    public void filldistable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblpres1.getModel();
        dtm.setRowCount(0);
        try
        {
            pst = conn.prepareStatement("select name,description from diseases");
            rst = pst.executeQuery();
            while(rst.next())
            {
                model1.addRow(new Object [] {rst.getString("name"),rst.getString("description")});
            }
            tblpres1.setModel(model1);
        }
        catch(SQLException e)
        {
            System.out.print("Error at filldistable: "+e);
        }
    }
    public void loaddis()
    {
        cmbdisease.removeAllItems();
        try 
        {
            stmt = conn.createStatement();
            String query = "Select name from diseases";
            rst = stmt.executeQuery(query);
            while(rst.next())
            {
                cmbdisease.addItem(rst.getString("name"));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addprescriptions()
    {
        String presname = txtppname.getText();
        String purpose = cmbdisease.getSelectedItem().toString();
        String output=null;
        try
        {
            pst = conn.prepareStatement("select pname from prescriptions where pname = ? and purpose = ?");
            pst.setString(1, presname);
            pst.setString(2, purpose);
            rst = pst.executeQuery();
            while(rst.next())
            {
                output = rst.getString("pname");
            }
            if(output !=null)
            {
                JOptionPane.showMessageDialog(null, "Prescription already added");
            }
            else
            {
                pst = conn.prepareStatement("insert into prescriptions values (?,?)");
                pst.setString(1, presname);
                pst.setString(2, purpose);
                int i = pst.executeUpdate();
                if (i>0)
                {
                    JOptionPane.showMessageDialog(null,"Medicine added successfully ");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Error while adding medicine ");
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Error at add prescription: "+e);
        }
    }
    
    public void fillprestable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblpres.getModel();
        dtm.setRowCount(0);
        try
        {
            pst = conn.prepareStatement("select pname,purpose from prescriptions");
            rst = pst.executeQuery();
            while(rst.next())
            {
                model.addRow(new Object [] {rst.getString("pname"),rst.getString("purpose")});
            }
            tblpres.setModel(model);
        }
        catch(SQLException e)
        {
            System.out.print("Error at fillprestable: "+e);
        }
    }
    
    public void loaddelmed()
    {
        ArrayList<String> list2 = new ArrayList<>();
        try
        {
            pst = conn.prepareStatement("select pname from prescriptions");
            rst = pst.executeQuery();
            while(rst.next())
            {
                list2.add(rst.getString("pname"));
            }
        }
        catch(SQLException e)
        {
             System.out.println("Can't fetch presname in delete combo: "+e);
        }
        cmbpresname.setModel(new DefaultComboBoxModel(list2.toArray()));
    }
        
    public void loaddeldis()
    {
        cmbdiseasename.removeAll();
        ArrayList<String> list2 = new ArrayList<>();
        try
        {
            pst = conn.prepareStatement("select name from diseases");
            rst = pst.executeQuery();
            while(rst.next())
            {
                list2.add(rst.getString("name"));
            }
            filldistable();
        }
        catch(SQLException e)
        {
             System.out.println("Can't fetch disease name in delete combo: "+e);
        }
        cmbdiseasename.setModel(new DefaultComboBoxModel(list2.toArray()));
    }
    
    public void deletepres()
    {
        try
        {
            String delpresname = cmbpresname.getSelectedItem().toString();
            pst = conn.prepareStatement("delete from prescriptions where pname = ?");
            pst.setString(1, delpresname);
            int i =pst.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null, "Medicine deleted successfully.");
            }
        }
        catch(SQLException e)
        {
            System.out.println("Error at deletepres: "+e);
        }
    }
    
    public void adddisease()
    {
        if(!txtdiseasename.getText().equals("")) 
        {
            if(txtdesc.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Disease Description");
            }
            else
            {
                String presname = txtdiseasename.getText();
                String purpose = txtdesc.getText();
                String output=null;
                try
                {
                    pst = conn.prepareStatement("select name from diseases where name = ? ");
                    pst.setString(1, presname);
                    rst = pst.executeQuery();
                    while(rst.next())
                    {
                        output = rst.getString("name");
                    }
                    if(output !=null)
                    {
                        JOptionPane.showMessageDialog(null, "Disease already added");
                    }
                    else
                    {
                        pst = conn.prepareStatement("insert into diseases(name,description) values (?,?)");
                        pst.setString(1, presname);
                        pst.setString(2, purpose);
                        int i = pst.executeUpdate();
                        if (i>0)
                        {
                            JOptionPane.showMessageDialog(null,"Ailment added successfully ");
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Error while adding disease ");
                        }
                    }
                }
                catch(SQLException e)
                {
                    System.out.println("Error at add disease: "+e);
                }
            }
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Enter Disease Name");
        }
        
    }
    public void deletedis()
    {
        try
        {
            String delpresname = cmbdiseasename.getSelectedItem().toString();
            pst = conn.prepareStatement("delete from diseases where name = ?");
            pst.setString(1, delpresname);
            int i =pst.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null, "Ailment deleted successfully.");
                filldistable();
            }
            
        }
        catch(SQLException e)
        {
            System.out.println("Error at deletedis: "+e);
        }
    }
    
    
    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        logout();
        System.exit(0);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
              fillprestable();
               loaddelmed();
             loaddis();
        filldistable();
            loaddeldis();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void DiseaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiseaseMouseClicked
        filldistable();
        loaddeldis();
    }//GEN-LAST:event_DiseaseMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        deletedis();
        filldistable();
        loaddeldis();
    }//GEN-LAST:event_jButton9ActionPerformed
//add disease
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        adddisease();
        filldistable();
        loaddeldis();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void PrescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionMouseClicked
        fillprestable();
        loaddelmed();
    }//GEN-LAST:event_PrescriptionMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        deletepres();
        loaddelmed();
        fillprestable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(txtppname.getText().length() !=0)
        {
            addprescriptions();
            DefaultTableModel dtm = (DefaultTableModel) tblpres.getModel();
            dtm.setRowCount(0);
            fillprestable();
            loaddelmed();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please fill the medicine name");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        resetdoc();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btndocsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocsaveActionPerformed
        if((txtdoc.getText()==null) ||(txtmob.getText() == null) ||(txtmrno.getText() == null) ||(txtemail.getText()==null)
            ||(txtspec.getText() == null)||(txtaddress.getText() == null)||(cmbdegree.getSelectedIndex()==-1))
        {
            JOptionPane.showMessageDialog(null, "Fill in all the details");
        }
        else
        {
            String docname = txtdoc.getText();
            String mob = txtmob.getText();
            String mrno = txtmrno.getText();
            String email = txtemail.getText();
            String degree = cmbdegree.getSelectedItem().toString();
            String add = txtaddress.getText();
            String spec = txtspec.getText();
            try
            {
                System.out.println(docname);
                pst = conn.prepareStatement("select dname from doctor where dname = ?");
                pst.setString(1,docname);
                rst = pst.executeQuery();
                if(rst.next())
                {
                    System.out.println(rst.getString("dname"));
                    pst = conn.prepareStatement("update doctor set dname = ? , mobile=? , email=? , degree=?"
                        + ", mrno=?, special=?, address=? where dname=?");
                    pst.setString(1, docname);
                    pst.setString(2, mob);
                    pst.setString(3, email);
                    pst.setString(4, degree);
                    pst.setString(5,mrno);
                    pst.setString(6, spec);
                    pst.setString(7,add);
                    pst.setString(8,docname);
                    int i= pst.executeUpdate();
                    if(i>0)
                    {
                        JOptionPane.showMessageDialog(null, "Doctor Updated Successfully");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error adding Doctor");
                    }
                }
                else
                {
                    pst = conn.prepareStatement("insert into doctor(dname,mobile,email,degree,mrno,special,address) values (?,?,?,?,?,?,?)");
                    pst.setString(1, docname);
                    pst.setString(2, mob);
                    pst.setString(3, email);
                    pst.setString(4, degree);
                    pst.setString(5,mrno);
                    pst.setString(6, spec);
                    pst.setString(7,add);
                    int i= pst.executeUpdate();
                    if(i>0)
                    {
                        JOptionPane.showMessageDialog(null, "Doctor Added Successfully");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error adding Doctor");
                    }
                }

            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btndocsaveActionPerformed

    private void txtdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocActionPerformed

    private void btnchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangepassActionPerformed
        if((txtchangepasspass.getText().equals(""))||(txtchangepasspass.getText().equals(""))||(txtchangepassusrname.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Please fill the details");
        }
        else
        {
            int lid=0;
            try
            {
                stmt = conn.createStatement();
                String query = "Select loginid from login where username='"+txtchangepassusrname.getText()+"' and password='"+txtchangepasspass.getText()+"'";
                rst = stmt.executeQuery(query);
                while(rst.next()){
                    lid = rst.getInt("loginid");
                }
                if(lid ==0 )
                {
                    JOptionPane.showMessageDialog(null, "Username Password Combination Invalid");
                }
                else
                {
                    query = "Update login set password='"+txtchangepassnewpass.getText()+"' where loginid="+lid;
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Password changed");
                }
            }
            catch(SQLException ex)
            {
                Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtchangepassnewpass.setText("");
            txtchangepasspass.setText("");
            txtchangepassusrname.setText("");
        }
    }//GEN-LAST:event_btnchangepassActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtchangepassnewpass.setText("");
        txtchangepasspass.setText("");
        txtchangepassusrname.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        new HomeGUI(suser,stype,Integer.toString(sessionid)).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnhomelogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomelogoutActionPerformed
        logout();
    }//GEN-LAST:event_btnhomelogoutActionPerformed

    public void resetdoc()
    {
        txtdoc.setText(null);
        txtmob.setText(null);
        txtmrno.setText(null);
        txtemail.setText(null);
        cmbdegree.setSelectedIndex(0);
        txtspec.setText(null);
        txtaddress.setText(null);
    }
   
    public void logout()
    {
        try 
        {
            stmt = conn.createStatement();
            String query = "update session set logoffat=NOW() where sid='"+sessionid+"'";
            stmt.executeUpdate(query);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Login("").setVisible(true);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Nimbus".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
                //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() {
                new AdminPanel("","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Disease;
    private javax.swing.JPanel DocDetails;
    private javax.swing.JPanel Prescription;
    private javax.swing.JPanel Users;
    private javax.swing.JButton btnchangepass;
    private javax.swing.JButton btndocsave;
    private javax.swing.JButton btnhomelogout;
    private javax.swing.JComboBox<String> cmbdegree;
    private javax.swing.JComboBox<String> cmbdisease;
    private javax.swing.JComboBox<String> cmbdiseasename;
    private javax.swing.JComboBox<String> cmbpresname;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblpres;
    private javax.swing.JTable tblpres1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JPasswordField txtchangepassnewpass;
    private javax.swing.JPasswordField txtchangepasspass;
    private javax.swing.JTextField txtchangepassusrname;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtdiseasename;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtmrno;
    private javax.swing.JTextField txtppname;
    private javax.swing.JTextField txtspec;
    // End of variables declaration//GEN-END:variables

    

    
}
